---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    linkerd.io/inject: enabled
  name: servicemesh
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  namespace: servicemesh
  labels:
    app: server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - server
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: server
          imagePullPolicy: Always
          image: localhost:5005/seminar/server:latest
          args: [ "--grpc"]
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi
          ports:
            - containerPort: 8080
            - containerPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: server
  namespace: servicemesh
  labels:
    app: server
spec:
  selector:
    app: server
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: app
    - protocol: TCP
      port: 9000
      targetPort: 9000
      name: monitoring
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: service-mesh-server-monitor
  namespace: servicemesh
  labels:
    release: prometheus
spec:
  endpoints:
    - path: /metrics
      port: monitoring
      scheme: http
      scrapeTimeout: 30s
  namespaceSelector:
    matchNames:
      - servicemesh
  selector:
    matchLabels:
      app: server
