---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  namespace: rest
  labels:
    app: client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          imagePullPolicy: Always
          image: localhost:5005/seminar/client:latest
          args: [ "--rest" ]
          env:
            - name: REST_ADDRESS
              value: server:8081
            - name: DEFAULT_WAIT_TIME
              value: 1ms
          ports:
            - containerPort: 9000
              name: monitoring
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: rest-client-monitor
  namespace: rest
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: client
  namespaceSelector:
    matchNames:
      - rest
  podMetricsEndpoints:
    - port: monitoring
