{
 "title": "Seminar",
 "time": { "from": "2023-12-29T16:45:00.000Z", "to": "2023-12-29T17:10:00.000Z" },
 "templating": {
  "list": [
   {
    "name": "Namespace",
    "query": "rest, default, headless, servicemesh"
   }
  ]
 },
 "panels": [
  { "title": "$Namespace", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "Namespace" },
  {
   "title": "Pods Running",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "count(container_memory_usage_bytes{container=\"client\", namespace=\"$Namespace\"})",
     "legendFormat": "Client"
    },
    {
     "expr": "count(container_memory_usage_bytes{container=\"server\", namespace=\"$Namespace\"})",
     "legendFormat": "Server"
    }
   ]
  },
  {
   "title": "RPS per Pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "rate(grpc_server_handled_total{namespace=\"$Namespace\"}[$__rate_interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(grpc_client_handling_seconds_bucket{namespace=\"$Namespace\"}[$__rate_interval])))",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(grpc_client_handling_seconds_bucket{namespace=\"$Namespace\"}[$__rate_interval])))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(grpc_client_handling_seconds_bucket{namespace=\"$Namespace\"}[$__rate_interval])))",
     "legendFormat": "P99"
    }
   ]
  }
 ]
}