apiVersion: ctlptl.dev/v1alpha1
kind: Registry
name: seminar
port: 5005
---
apiVersion: ctlptl.dev/v1alpha1
kind: Cluster
product: kind
registry: seminar
kindV1Alpha4Cluster:
  name: seminar
  nodes:
    - role: control-plane
    - role: worker
    - role: worker
    - role: worker
    - role: worker
